### ISSUE TITLE
Values of some variables set to zero/near zero.

### ISSUE THREAD

**Issue by imcslatte** [ERDDAP/erddap#221] opened 2024-10-28 18:21 UTC
**Describe the bug**
The variables of some variables in my ERDDAP dataset are set to zero/ near zero for requests of more than 1e7 rows. 

**To Reproduce**

I ran into some unexpected behavior for a dataset we have on our ERDDAP server. 

https://tds.marine.rutgers.edu/erddap/tabledap/CORA_Profiles_ECCOFSgrid.html

If I set the parameters to extract data from 2019/06/01 to 2019/10/01:

https://tds.marine.rutgers.edu/erddap/tabledap/CORA_Profiles_ECCOFSgrid.nc?time%2Clatitude%2Clongitude%2Cdepth%2Cprovenance%2CI%2CJ&time%3E=2019-06-01T00%3A00%3A00Z&time%3C=2019-10-01T23%3A54%3A00Z

The values in the variable provenance (range 800:809) after row 1e7 in the file are set to zero or near zero. The same goes for I and J. The other variables are fine. 

If I switch to the time period 2019/09/15 to 2019/10/01:

https://tds.marine.rutgers.edu/erddap/tabledap/CORA_Profiles_ECCOFSgrid.nc?time%2Clatitude%2Clongitude%2Cdepth%2Cprovenance%2CI%2CJ&time%3E=2019-09-15T00%3A00%3A00Z&time%3C=2019-10-01T23%3A54%3A00Z

The values that were set to zero previously.  are now within the expected range. 

In addition, I checked the source files, and there are no values outside the expected range. The values also look fine if I pull up a time series of the entire dataset as an ERDDAP graph. 

**Expected behavior**
I expect all the values in the data set to be returned for a given query. 

**Server**
https://tds.marine.rutgers.edu/erddap
erddap version 2.24

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome

**Additional context**

Datasets XML attached
[dataset_xml.txt](https://github.com/user-attachments/files/17547138/dataset_xml.txt)
Example data files. 

[CORA_SUBSET_ECCOFS_PR_20190120.zip](https://github.com/user-attachments/files/17547199/CORA_SUBSET_ECCOFS_PR_20190120.zip)

**Comment by ChrisJohnNOAA** [comment] 2024-11-14 18:44
@imcslatte I'm trying to reproduce the problem locally, but unable to so far. Would you be able to share some additional files from the dataset?

**Comment by ChrisJohnNOAA** [comment] 2024-11-14 18:59
Do you see issues with all export formats, or specifically with nc?

**Comment by imcslatte** [comment] 2024-11-14 20:52
Hi Chris,

I saw issues with NetCDF and mat files, but I didn't try any others.

There's a year of data at:

https://marine.rutgers.edu/~hunter/stuff/testdata.tar.gz

Let me know if you have any problems accessing. Where you able to reproduce the problem from our server?


Thanks for looking into it.

Eli



________________________________

**Comment by ChrisJohnNOAA** [comment] 2024-11-14 22:08
Thanks for the files. I'll give that a try. I tried downloading a csv from your sever which as far as I could tell had all of the proper data. I did not try an nc file. If I can't reproduce locally with the new files I'll try your sever again with other file formats.

**Comment by ChrisJohnNOAA** [comment] 2024-11-18 17:01
I was able to reproduce the problem with nc files and have a fix #229 .

This fix will be in the next release (2.26) which is currently expected in late January.

I was unable to reproduce the issue with .mat files either locally or on your server. If you are seeing an issue with mat files could you confirm what bad data you are seeing?

**Closed** 2024-11-19 00:10 UTC

**Comment by imcslatte** [comment] 2024-11-19 13:24
Thanks Chris,

It turns out there was not an issue with the mat files. It was a miscommunication.


Eli

________________________________
