### ISSUE TITLE
Strange case where querying a dataset retrun erroneous  404 No Rows result

### ISSUE THREAD

**Issue by MarcoAlbaETT** [ERDDAP/erddap#152] opened 2024-05-23 11:04 UTC
(please forgive me, but is not easy to define a title for this problem)
**Describe the bug**
With a dataset defined as:
```
<dataset type="EDDTableFromMultidimNcFiles" datasetID="TS_ATMP_AAD" active="true">
	<reloadEveryNMinutes>60</reloadEveryNMinutes>
	<fileDir>/Data/param/TS/ATMP/aad/</fileDir>
	<fileNameRegex>.*\.nc</fileNameRegex>
	<recursive>true</recursive>
	<pathRegex>.*</pathRegex>
	<metadataFrom>last</metadataFrom>
	<standardizeWhat>0</standardizeWhat>
	<removeMVRows>true</removeMVRows>
	<sortFilesBySourceNames></sortFilesBySourceNames>
	<fileTableInMemory>false</fileTableInMemory>
	<addAttributes>
		<!-- omississ -->
	</addAttributes>        
	<dataVariable>
		<sourceName>global:platformCode</sourceName>
		<destinationName>PLATFORMCODE</destinationName>
		<dataType>String</dataType>
		<addAttributes>
			<att name="long_name">EMODnet Platform Code</att>
			<att name="cf_role">timeseries_id</att>
		</addAttributes>
	</dataVariable>    
	<dataVariable>
		<sourceName>="aad"</sourceName>
		<destinationName>SOURCE</destinationName>
		<dataType>String</dataType>
		<addAttributes>
			<att name="long_name">source</att>
		</addAttributes>
	</dataVariable>      
	<dataVariable>
		<sourceName>variable:ATMP:sensor</sourceName>
		<destinationName>SENSOR</destinationName>
		<dataType>String</dataType>
		<addAttributes>
			<att name="long_name">Platform Sensor</att>
		</addAttributes>
	</dataVariable>    
	<dataVariable>
		<sourceName>TIME</sourceName>
		<destinationName>time</destinationName>
		<dataType>double</dataType>
		<addAttributes>
			<att name="_ChunkSizes">null</att>
		</addAttributes>
	</dataVariable>
	<dataVariable>
		<sourceName>TIME_QC</sourceName>
		<destinationName>TIME_QC</destinationName>
		<dataType>short</dataType>
		<addAttributes>
			<att name="_ChunkSizes">null</att>
		</addAttributes>
	</dataVariable>
	<dataVariable>
		<sourceName>DEPTH</sourceName>
		<destinationName>depth</destinationName>
		<dataType>double</dataType>
		<addAttributes>
			<att name="_ChunkSizes">null</att>
		</addAttributes>
	</dataVariable>
	<dataVariable>
		<sourceName>DEPTH_QC</sourceName>
		<destinationName>DEPTH_QC</destinationName>
		<dataType>short</dataType>
		<addAttributes>
			<att name="_ChunkSizes">null</att>
			<att name="standard_name">depth</att>
		</addAttributes>
	</dataVariable>
	<dataVariable>
		<sourceName>LATITUDE</sourceName>
		<destinationName>latitude</destinationName>
		<dataType>double</dataType>
		<addAttributes>
			<att name="_ChunkSizes">null</att>
			<att name="latitude.reference_datum">null</att>
			<att name="latitude_reference_datum">geographical coordinates, WGS84 projection</att>
		</addAttributes>
	</dataVariable>    
	<dataVariable>
		<sourceName>LONGITUDE</sourceName>
		<destinationName>longitude</destinationName>
		<dataType>double</dataType>
		<addAttributes>
			<att name="_ChunkSizes">null</att>
			<att name="latitude.reference_datum">null</att>
			<att name="latitude_reference_datum">geographical coordinates, WGS84 projection</att>
		</addAttributes>
	</dataVariable>
	<dataVariable>
		<sourceName>POSITION_QC</sourceName>
		<destinationName>POSITION_QC</destinationName>
		<dataType>short</dataType>
		<addAttributes>
			<att name="_ChunkSizes">null</att>
		</addAttributes>
	</dataVariable>
	<dataVariable>
		<sourceName>ATMP</sourceName>
		<destinationName>ATMP</destinationName>
		<dataType>double</dataType>
		<addAttributes>
			<att name="_ChunkSizes">null</att>
		</addAttributes>
	</dataVariable>
	<dataVariable>
		<sourceName>ATMP_QC</sourceName>
		<destinationName>ATMP_QC</destinationName>
		<dataType>short</dataType>
		<addAttributes>
			<att name="_ChunkSizes">null</att>
		</addAttributes>
	</dataVariable>
	<dataVariable>
		<sourceName>ATMP_DM</sourceName>
		<destinationName>ATMP_DM</destinationName>
		<dataType>char</dataType>
		<addAttributes>
			<att name="_ChunkSizes">null</att>
		</addAttributes>
	</dataVariable>
	<dataVariable>
		<sourceName>=var p=row.columnString("global:platformCode");var s="aad";var x="https://data-erddap.emodnet-physics.eu/erddap/tabledap/EP_PLATFORMS_METADATA.htmlTable?&amp;PLATFORMCODE=%22"+p+"%22&amp;integrator_id=%22"+s+"%22&amp;distinct()";return x</sourceName>
		<destinationName>url_metadata</destinationName>
		<dataType>String</dataType>
		<addAttributes>
			<att name="long_name">Metadata Link</att>
		</addAttributes>
	</dataVariable>
	<dataVariable>
		<sourceName>=25</sourceName>
		<destinationName>qc_entity</destinationName>
		<dataType>int</dataType>
		<addAttributes>
			<att name="qc_reference_table">"https://er2webapps.emodnet-physics.eu/erddap/tabledap/qc_reference_table.htmlTable</att>
		</addAttributes>
	</dataVariable>
</dataset>
```
Querying dataset sometimes return a wrong 404 - No Rows, based on the type of field requested and the type of constrains used.

I've found this problem when trying to make this query:
https://er1webapps.emodnet-physics.eu/erddap/tabledap/TS_ATMP_AAD.htmlTable?url_metadata&PLATFORMCODE=%22Casey%22&distinct()
and discovered that it works if I change it like:
https://er1webapps.emodnet-physics.eu/erddap/tabledap/TS_ATMP_AAD.htmlTable?url_metadata&PLATFORMCODE=%22Casey%22&time%3E=0&distinct()

See next section **To Reproduce** for some more example

**To Reproduce**
I'm using this dataset as an example:
https://er1webapps.emodnet-physics.eu/erddap/tabledap/PR_PSAL_PANGAEACASES.html

**KO:** https://er1webapps.emodnet-physics.eu/erddap/tabledap/TS_ATMP_AAD.htmlTable?url_metadata&PLATFORMCODE=%22Casey%22&distinct()
**OK:** https://er1webapps.emodnet-physics.eu/erddap/tabledap/TS_ATMP_AAD.htmlTable?url_metadata&PLATFORMCODE=%22Casey%22&time%3E=0&distinct()

**KO:** https://er1webapps.emodnet-physics.eu/erddap/tabledap/TS_ATMP_AAD.htmlTable?SOURCE&SOURCE=%22aad%22&distinct()
**OK:** https://er1webapps.emodnet-physics.eu/erddap/tabledap/TS_ATMP_AAD.htmlTable?SOURCE&distinct()

**KO:** https://er1webapps.emodnet-physics.eu/erddap/tabledap/TS_ATMP_AAD.htmlTable?url_metadata&PLATFORMCODE=%22Casey%22
**OK:** https://er1webapps.emodnet-physics.eu/erddap/tabledap/TS_ATMP_AAD.htmlTable?url_metadata&PLATFORMCODE=%22Casey%22&time%3E=0

**KO:** https://er1webapps.emodnet-physics.eu/erddap/tabledap/TS_ATMP_AAD.htmlTable?url_metadata&PLATFORMCODE=%22Casey%22&SENSOR%3E=%22%22
**OK:** https://er1webapps.emodnet-physics.eu/erddap/tabledap/TS_ATMP_AAD.htmlTable?SENSOR%2Curl_metadata&PLATFORMCODE=%22Casey%22&SENSOR%3E=%22%22

**Expected behavior**
all querys must return results

**Screenshots**
no applicable

**Server**
I'm using ERDDAP Version 2.23 in a docker container using axiom/docker-erddap:2.23-jdk17-openjdk image

**Desktop (please complete the following information):**
- Windows, Linux
- Any Browser

**Additional context**

**Comment by ChrisJohnNOAA** [comment] 2024-06-21 19:04
I believe I've reproduced the problem locally. I think the issue is if a request only contains script/derived variables, it errors. This is because when the code loads from the nc file it sees no variables to load, and so returns there's no data.

**Comment by ChrisJohnNOAA** [comment] 2024-06-26 02:41
I have a fix for this in my branch here: https://github.com/ChrisJohnNOAA/erddap/tree/multidimNcFiles

I expect this to be in the 2.25 release. (Note 2.24 is already built and tested, and will be announced soon).

**Closed** 2024-07-11 20:48 UTC
Labels: bug
